import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import {HomepageContextProvider} from "../../components/Context/HomepageContextProvider";
import {createClient} from "@/lib/supabase/server";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default async function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {

    const supabase = await createClient();
    const user = (await supabase.auth.getUser()).data.user

    return (
        <html lang="en">
        <body className={`antialiased`}>
        <HomepageContextProvider authUser={user}>
            {children}
        </HomepageContextProvider>
        </body>
        </html>
    );
}
