import type {Metadata} from "next";
import React from "react";
import Header from "../../../components/Header/HeaderComponent";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function LandingPageLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <>
            <Header/>
            {children}
        </>


    );
}
