import type {Metadata} from "next";
import React from "react";
import DashboardWrapper from "../../../components/Dashboard/DashboardWrapper";
import {DashboardContextProvider} from "../../../components/Dashboard/Context/DashboardContextProvider";
import {createClient} from "@/lib/supabase/server";
import {redirect} from "next/navigation";
import ToastProvider from "../../../components/ToastProvider";
import PostHogIdentity from "../../../components/Analytics/PostHogIdentity";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default async function DashboardLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    const supabase = await createClient();
    const {data: {user}, error: userError} = await supabase.auth.getUser()
    if (!user || userError) {
        console.log("Failed to fetch user: ", userError)
        redirect("/")
    }

    const {data: {session}, error: sessionError} = await supabase.auth.getSession()
    if (sessionError) {
        console.log("Failed to fetch auth token: ", sessionError)
    }
    const accessToken = session?.access_token ?? null

    const {
        data: profile,
        error: profileError
    } = (await supabase.from("profiles").select("first_name, plan").eq("user_id", user.id).maybeSingle())
    if (profileError) {
        console.log("Failed to load profile: ", profileError)
    }


    return (
        <DashboardContextProvider jwkToken={accessToken} authUser={user} userProfile={profile}>
            <PostHogIdentity userId={user.id}/>
            <DashboardWrapper>
                {children}
                <ToastProvider/>
            </DashboardWrapper>
        </DashboardContextProvider>


    );
}
