import type {Metadata} from "next";
import React from "react";
import DashboardWrapper from "../../../components/Dashboard/DashboardWrapper";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function DashboardLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (

            <DashboardWrapper>
                {children}
            </DashboardWrapper>


    );
}
