import type {Metadata} from "next";
import React from "react";
import DashboardWrapper from "../../../components/Dashboard/DashboardWrapper";
import {cookies} from "next/headers";
import {DashboardContextProvider} from "../../../components/Dashboard/Context/DashboardContextProvider";
import {createClient} from "@/lib/supabase/server";
import {redirect} from "next/navigation";
import ToastProvider from "../../../components/ToastProvider";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default async function DashboardLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    const cookieStore = await cookies()
    const cookie = cookieStore.get(process.env.JWK_TOKEN_KEY!)?.value ?? null
    let cleanToken = null
    if(cookie){
        let decodedValue = decodeURIComponent(cookie);
        if (decodedValue.startsWith("base64-")) {
            const b64Data = decodedValue.replace("base64-", "");
            decodedValue = atob(b64Data);
        }
        const parsed = JSON.parse(decodedValue);
        if (Array.isArray(parsed)) {
            cleanToken = parsed[0]
        } else if (parsed && parsed.access_token) {
            cleanToken = parsed.access_token;
        }

    }
    const supabase = await createClient();
    const user = (await supabase.auth.getUser()).data.user
    if(!user){
        redirect("/")
    }





    return (
    <DashboardContextProvider jwkToken={cleanToken} authUser={user}>
        <DashboardWrapper>
            {children}
            <ToastProvider/>
        </DashboardWrapper>
    </DashboardContextProvider>



    );
}
